# Data sources
I. Introduction 
 A motor vehicle accident can have a large number of factors that lead to it. A collection of a series of such accidents and understanding the pattern (if any)  with respect to the location of the accident, the time at which the accident has taken place and other contributing factors like which vehicle has collided with the motor vehicle that led to the accident can help us understand the correlation between these factors and the accident. This information can be of great insight to both the common people and the police officers, if perceived in the right way. Firstly, it helps the common man by giving a caveat to be more cautious while driving around the accident prone area at a particular point of time. Secondly, it would help police officers in two ways - to keep and check on safety of the people, by monitoring the contributing factors of the accident in the accident prone locations at a particular time and also, to manage their manpower well, more police officers can be put to work at accident prone areas compared to the other areas. This is driving factor behind the project that we aim to work on, to study the pattern of motor vehicle accidents that take place in New York City to help understand and organise resources to reduce accidents

 With this study, we try to answer the following questions:
 1. Is the number of people injured or killed by motor vehicle accidents impacted by the time and day at which the accident has occurred.
 2. Are there any underlying contributing reasons that are resulting in more accidents?
 3. Does the severity of the accident have a correlation with the location at which it has taken place? For instance, do accidents in Manhattan have a higher death ratio compared to  accidents in the Bronx?
 4. Is there any pattern of the vehicles that hit the motor vehicles? For instance, do they get hit by sedans more than trucks?

 Analysis of the dataset to  answer these questions  would give us a better insight about how the common man can be more careful to avoid accidents and also to the police in ensuring our safety.


 II. Data sources
 The dataset chosen for this study is taken from the NYC Open Data. It is owned by NYC Open Data and is provided by the New York Police Department(NYPD). The dataset is a table where each row of the table represents a crash event. It contains the information from all the police reported motor vehicle collisions in NYC.  In cases where someone is injured or killed, or a damage worth $1000 a police report is required - MV104-AN.  The dataset is subjected to change where there is any update in the police report  (MV104-AN) with the revised crash details.  It was created in April, 2014 and is a large dataset with 1.84Million entries and 29 columns.

 Why and how is it collected?
 The police department implemented TrafficStat using the CompStats model to work towards the safety of people and to maintain uniformity in which data related to motor vehicles  is collected. Initially, they used a TAMS- Traffic Management Systems to collect traffic data using a few details around the collision, but later on when they decided to work towards the Vision Zero- to ensure zero fatalities,  the MV-104AN form was filled in a much more detailed manner for all the vehicle collisions that occured. The TAMS model was eliminated and FORMS - Finest Online Records Management System was introduced in 2016 to store data electronically. The policemen use a department cellphone or computer to enter all the MV-104AN data fields which are stored in the Department crime data warehouse. This ensures that the entire MV-104AN form with all the details is stored securely, which can be used to do a detailed traffic safety analysis to work towards the Vision Zero goal.

 The data we would work on:
 Since the dataset is enormous, we have decided to work on a  complete year of data, starting from 1, January 2020 to 31, December 2020. This data contains ______ entries. Studying the recent year of data gives a clear understanding of the latest trends in the collisions, given the growth of traffic every year.

 Problems/Issues:
 A few of the fields in the Dataset are missing which are being imputed/eliminated based on the type of question we plan to answer.


 A brief overview of the dataset:
 Dataset contains 29 attributes, a brief overview of all these are described below:

 Column Name 			Description
 Crash Date			Date of collision
 Crash Time			Time of collision
 Borough				Place of collision
 Zip Code			Postal code where the collision occurred
 Latitude			Latitude on Coordinate System
 Longitude			Longitude on Global Coordinate System
 On Street Name			Street on which collision occurred
 Cross Street Name		Nearest cross Street where collision occurred.
 Off Street name			Street Address
 Number of people,pedestrians, cyclist, motorist injured			Details on the number of people injured in each category
 Number of people,pedestrians, cyclist, motorist killed			Details on the number of people killed in each category
 Contributing factors vehicle 1,2,3,4,5			Factors which contribute to the collision
 Collision ID			Unique Record code generated by system
 Vehicle Type Code 1,2,3,4,5			Type of vehicle
