# Data transformation

Haven't completed the description for Data Transformation Chapter yet.

```{r}
library(readr)
library(tidyverse)

raw_data <- read_csv("Motor_Vehicle_Collisions_-_Crashes.csv")
cat("Number of Rows:", nrow(raw_data),'\n')
cat("Number of Columns:", ncol(raw_data))

```


```{r}
raw_data %>%
  head(5)
```


```{r}
raw_data$`CRASH DATE` <- as.Date(raw_data$`CRASH DATE`, format= "%m/%d/%Y")
data2020 <- raw_data %>%
  filter(`CRASH DATE` >= as.Date("01/01/2020", format= "%m/%d/%Y"))%>%
  filter(`CRASH DATE` <= as.Date("12/31/2020", format= "%m/%d/%Y")) 

write.csv(data2020,"./resources/2020Motor_Vehicle_Collisions_.csv", row.names = FALSE)
```

```{r}
cat("Number of Rows:", nrow(data2020),'\n')
cat("Number of Columns:", ncol(data2020))
abbreviate(colnames(data2020))
```



```{r}
colnames(data2020) <- c("Date","Time","BOR","ZIP","LAT","LONG","LOC","ONSN","CRSN","OFFSN","#PI","#PK","#PEDI","#PEDK","#CI","#CK","#MI","#MK","CFV1","CFV2","CFV3","CFV4","CFV5","id","VTC1","VTC2","VTC3","VTC4","VTC5")
colnames(data2020)
```


```{r}
write.csv(data2020,"./resources/Column_Transformed_2020Motor_Vehicle_Collisions_.csv", row.names = FALSE)
```


```{r}
##Create day, month, year columns
data2020 %>%
  mutate(Day = format(`Date`, "%D"), 
         Month = format(`Date`, "%m"), 
         Year = format(`Date`, "%Y"))
```


