# Conclusion

This project has been a great source of learning, formulation, and application of ideas and thoughts to a real-world problem. A few limitations, future directions, and lessons learned are mentioned below. 

One of the limitations that we have faced while working on this dataset is that the dataset is large, so we had to refine our analysis of accidents in the city of New York to one full year of data, namely 2020. The reason for choosing to study a full year of data is that we wanted to understand how traffic and accidents are affected by different months of the year. For this reason, we could not analyze the latest year - 2021 (January to December), which would not have been possible with 2021. 

As part of the future directions, we want to analyze multiple years' data and compare different years' data amongst other years, this would help analyze the growth in traffic and accident rate in New York over a range of multiple years. This would also be instrumental in studying the accident patterns and traffic growth before and after Covid 2020. Thus, analyzing a COVID-19 data set along with this data set could be a great start for the next stage. From a technical standpoint, we want to incorporate more graphs, namely Alluvial diagrams, Mosaic plots to study the underlying patterns in the data in a better manner.

While working on this project, we have learned how to use the techniques and graphs learned in class on a bigger, impactful real-world dataset that has the potential to help the community. It helped us study the trends in the number of accidents in New York city based on different boroughs. We also observed how accidents can be affected by the time of the day, which can be used by the police to understand the areas and contributing factors for accidents more in depth, contributing towards the improvement of the public safety on the streets in New York. Finally, we have also learned how to work more effectively as a team, discuss ideas openly, and incorporate those ideas and suggestions into a project.
