--- 
title: "NYC Motor Vehicle Crashes Analysis"
author: "Maxwell Zhou, Xin Ye, and Kiranmai Vasireddy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction 
A motor vehicle accident can have a large number of factors that lead to it.  We can study a large sample of these accidents that occur in New York City and try to further understand any patterns in the data.  Factors such as the location of the accident, the time at which the accident occurs, and other contributing factors (vehicle types involved in the accident, the reason for the occurrence of the accident, etc.) can help us understand and visualize the causes and effects of these accidents in greater depth. This information can be of great insight to drivers, motorists, pedestrians, and even police officers. First, it helps the normal people by allowing them to  be more cautious while driving around accident prone areas during certain time periods. Second, it would help police officers in two ways - to help them in protecting the safety  of the pedestrians and other people in the area by monitoring the contributing factors of the accident in the accident prone locations at a particular time and also, to manage their manpower well (more police officers can be put to work at accident prone areas compared to the other areas). This is the driving factor behind the project that we aim to work on: to study the pattern of motor vehicle accidents that take place in New York City to help understand and organize resources to reduce accidents. Besides, our study could help the public to be aware of the most deadly accidents caused by different vehicle types and contributing factors and potentially reduce the occurrence of those accidents.

**With this study, we try to answer the following questions:**

1. How does the time of day and the day of the week impact the total number of accidents that occur and number of people injured or killed in those accidents?  

2. Which are some contributing factors and vehicle types that contribute to most accidents? Among all the contributing factors or vehicle types, which are more likely to cause deaths rather than injuries in these accidents? 

3. Is there any obvious geographic information of the accidents recorded by mistakes  in 2020 in New York? And are there any patterns on the distribution of those accidents in New York in 2020?

4. What contributing factors cause the most numbers of people injured and killed in accidents? What are the top 15 streets in each New York City borough by number of people injured and killed? Are there any patterns in the most dangerous streets?

By analyzing this dataset in depth, we can help to answer the questions above. The answers to those questions will allow the streets of New York City to be a safer place for everyone. 
